Repository AY1920S1-CS2103T-T12-4/main, pull requests merged in 2019-10, with the labels that each got.

#36 Add glossary for test and category
  docs/DeveloperGuide.adoc
Labels: documentation

#37 Progress for StartCommand (Flashcard Tests)
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#44 Import export commands
  build.gradle
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/FilePath.java
Labels: enhancement

#74 Update @@author tags
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
Labels: documentation

#83 added find category feature
  src/main/java/seedu/address/logic/commands/FindCategoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCategoryCommandParser.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/CategoryContainsAnyKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalFlashCardAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCategoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/flashcard/FlashCardTest.java
  src/test/java/seedu/address/model/flashcard/UniqueFlashCardListTest.java
  src/test/java/seedu/address/testutil/FlashCardBuilder.java
  src/test/java/seedu/address/testutil/TypicalFlashCards.java
Labels: type.Enhancement

#98 Flashcard Tests v1.2 progress
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/ShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/StartCommandTest.java
  src/test/java/seedu/address/model/FlashCardTestModelTest.java
  src/test/java/seedu/address/testutil/FlashCardTestListBuilder.java
Labels: type.Enhancement

#100 Gui draft 1
  .gitignore
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/category/UniqueCategoryList.java
  src/main/java/seedu/address/ui/CategoryListPanel.java
  src/main/java/seedu/address/ui/CategoryPanel.java
  src/main/java/seedu/address/ui/FlashCardListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/icon.png
  src/main/resources/view/CategoryListCard.fxml
  src/main/resources/view/CategoryListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#111 Add codacy badge
  README.adoc
Labels: documentation

#114 Deadline/Reminder mid-v1.3
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/deadline/TaskContainsAllKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalFlashCards.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: documentation, type.Enhancement

#113 Flashcard Tests mid-v1.3 progress
  README.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/StartCommandTest.java
  src/test/java/seedu/address/model/FlashCardTestModelTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: documentation, type.Enhancement

#146 DG for StartCommand
  docs/DeveloperGuide.adoc
  docs/diagrams/StartSequenceDiagram.puml
  docs/images/StartSequenceDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#149 Flashcard Tests v1.3 progress
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/ShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/KeyboardFlashCardsParser.java
  src/main/java/seedu/address/logic/parser/RateQuestionCommandParser.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/KeyboardFlashCardsParserTest.java
  src/test/java/seedu/address/model/FlashCardTestModelTest.java
Labels: type.Enhancement

#157 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: documentation, priority.High

#165 Update user guide, changed USAGE_MESSAGE
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
Labels: bug, documentation
