Repository AY1920S1-CS2103T-T12-4/main, pull requests merged in 2019-11, with the labels that each got.

#200 Implement defensive programming techniques
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/ShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/KeyboardFlashCardsParser.java
  src/main/java/seedu/address/logic/parser/RateQuestionCommandParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/test/java/seedu/address/logic/commands/StartCommandTest.java
  src/test/java/seedu/address/logic/parser/KeyboardFlashCardsParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Low

#223 Deadlines mid-v1.4
  docs/AboutUs.adoc
  docs/images/deadline-entered.png
  docs/images/deadline-entry.png
  docs/team/dalsontws.adoc
Labels: documentation

#220 Flashcard Tests mid-v1.4 progress
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/NextQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/ShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/SkipCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/KeyboardFlashCardsParser.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/DeadlineListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/KeyboardFlashCardsParserTest.java
Labels: bug, documentation

#231 Remove list hiding
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/NextQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#232 FlashCard Tests v1.4 progress
  docs/UserGuide.adoc
  docs/images/StartEmptyParam.png
  docs/images/StartWithTagParam.png
  src/main/java/seedu/address/logic/commands/EndTestCommand.java
  src/main/java/seedu/address/logic/commands/NextQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/ShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/KeyboardFlashCardsParser.java
  src/main/java/seedu/address/logic/parser/RateQuestionCommandParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/FlashCardTestModel.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/RateQuestionCommandTest.java
  src/test/java/seedu/address/testutil/FlashCardTestListBuilder.java
Labels: bug, documentation

#242 Documentation - dalsontws
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/BadFlashcard.png
  docs/images/BadFlashcardAdded.png
  docs/images/calendar.png
  docs/images/deadline-entered.png
  docs/images/deadline-entry.png
  docs/images/listbad.png
  docs/images/removebad.png
  docs/images/removebadsuccess.png
  docs/team/dalsontws.adoc
  src/main/java/seedu/address/model/deadline/BadQuestions.java
  src/main/java/seedu/address/model/deadline/DueDate.java
  src/main/java/seedu/address/ui/DeadlinePanel.java
  src/main/resources/view/DarkTheme.css
Labels: documentation

#241 Test Mode Documentation
  docs/UserGuide.adoc
  docs/images/EndCommand.png
  docs/images/EndResults.png
  docs/images/RateCommand.png
  docs/images/RateResults.png
  docs/images/ShowAnswerCommand.png
  docs/images/ShowAnswerResults.png
  docs/images/SkipCommand.png
  docs/images/SkipResults.png
  docs/images/StartResults.png
  src/main/java/seedu/address/logic/commands/RateQuestionCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
Labels: documentation

#244 Test mode DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StartCommandClassDiagram.puml
  docs/diagrams/StartSequenceDiagram.puml
  docs/diagrams/TestModeActivityDiagram.puml
  docs/images/StartCommandClassDiagram.png
  docs/images/TestModeActivityDiagram.png
  src/main/resources/images/Commands.png
Labels: documentation
